server:
  port: 8888
  
spring:  profiles:    active: native
  cloud:
    config:      server:        native:          search-locations: D:/Cursos/Alura/Spring Cloud/config-server/microservices-repo